version: 0.0
os: linux
files:
- source: /
  destination: /var/www/html/
hooks:
  AfterInstall:
  - location: scripts/before_install.sh
    timeout: 100
  ApplicationStart:
  - location: scripts/restart_httpd.sh
    timeout: 100
